name: build grpcio-tools wheel

on:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/grpcio-tools.yaml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/grpcio-tools.yaml"
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'
env:
  PACKAGE: grpcio-tools
jobs:
  check:
    name: Check if wheel exists
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.check.outputs.build }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check if exists
        id: check
        run: |
          pkg=${{ env.PACKAGE }}

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            version="${{ github.event.inputs.version }}"
          else
            version="latest"
          fi

          url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
          upstream_url="https://pypi.org/pypi/${pkg}/json"

          if [[ "${version}" == "latest" ]]; then
            version="$(curl -s ${upstream_url} | jq -r '.info.version')"
          fi

          if curl -Ls ${url} | grep -q grpcio_tools-${version}.*loongarch64; then
            echo "build=false" >> $GITHUB_OUTPUT
            echo "${platform} wheels already exists."
          else
            echo "build=true" >> $GITHUB_OUTPUT
            echo "${platform} wheels not found, continue building"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

  build:
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        python: ["cp310", "cp311", "cp312", "cp313", "cp314"]
        platform: ["manylinux", "musllinux"]
    if: needs.check.outputs.build == 'true'

    steps:
      - uses: Loongson-Cloud-Community/pypi@main
        with:
          name: ${{ env.PACKAGE }}
          version: ${{ env.VERSION }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: docker/setup-qemu-action@v3

      - name: Build wheel
        uses: loong64/cibuildwheel@v3.3.1
        env:
          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
          CIBW_ARCHS: "loongarch64"
          CIBW_BEFORE_BUILD: pip install 'setuptools<=75.1.0' wheel
          CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
          CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform }}_loongarch64"
          CIBW_ENVIRONMENT_PASS_LINUX: >
            PIP_INDEX_URL

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE }}-${{ env.VERSION }}-${{ matrix.python }}-${{ matrix.platform }}
          path: wheelhouse/*

  upload:
    needs: [build]
    runs-on: ubuntu-24.04
    if: needs.build.outputs.upload == 'true' && github.event_name != 'pull_request'
    
    steps:
      - name: Clean workspace
        run: safe-rm -rf * .*

      - uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.PACKAGE }}-*
          path: wheelhouse
          merge-multiple: true

      - name: Upload wheels
        run: |
          ls wheelhouse/*.whl || exit 1
          pip install twine==6.0.1
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
