name: 🧾 Update README (Bilingual Linked Version)

on:
  schedule:
   - cron: "0 3 * * *" 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*.yaml"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repository info
        id: repo
        run: |
          REPO_URL=$(git config --get remote.origin.url | sed 's/.git$//')
          echo "repo_url=${REPO_URL}" >> $GITHUB_OUTPUT

      - name: Generate bilingual README files
        run: |
          REPO_URL="${{ steps.repo.outputs.repo_url }}"
          mkdir -p tmp

          # ---------- English Version ----------
          {
            echo "# 🏗️ LoongArch Python Package Build CI"
            echo ""
            echo "[简体中文](./README_zh.md)"
            echo ""
            echo "This repository automatically builds and maintains **Python (pip) packages** for the **LoongArch (loongarch64)** architecture."
            echo ""
            echo "---"
            echo ""
            echo "## 📦 Supported Build Workflows"
            echo ""
            echo "| No. | Package | Workflow |"
            echo "|-----|----------|-----------|"

            i=1
            for f in $(ls .github/workflows/*.yaml | sort); do
              base=$(basename "$f")
              pkg=$(basename "$f" .yaml)
              # skip this workflow itself
              if [ "$base" = "README.yaml" ]; then
                continue
              fi
              link="$REPO_URL/blob/main/.github/workflows/$base"
              echo "| $i | $pkg | [${base}](${link}) |"
              i=$((i+1))
            done

            echo ""
            echo "_This table is automatically generated by GitHub Actions._"
            echo ""
            echo "---"
            echo ""
            echo "## ⚙️ Automation Details"
            echo ""
            echo "- Each package has a dedicated workflow under \`.github/workflows/\`."
            echo "- This workflow runs **daily** and regenerates this README when any workflow file is added or removed."
            echo "- The \`README.yaml\` itself is excluded from the list."
            echo ""
            echo "---"
            echo ""
            echo "## 🕒 Last Updated"
            echo ""
            echo "- UTC Time: \`$(date -u '+%Y-%m-%d %H:%M:%S')\`"
            echo "- Local Time (Asia/Shanghai): \`$(date '+%Y-%m-%d %H:%M:%S')\`"
          } > tmp/README.md

          # ---------- 中文版本 ----------
          {
            echo "# 🏗️ LoongArch Python 包构建自动化仓库"
            echo ""
            echo "[English](./README.md)"
            echo ""
            echo "本仓库用于自动构建和维护 **LoongArch（loongarch64）** 架构下的 **Python 第三方库（pip 包）**。"
            echo ""
            echo "---"
            echo ""
            echo "## 📦 当前支持的构建任务"
            echo ""
            echo "| 序号 | 包名称 | Workflow 文件 |"
            echo "|------|----------|----------------|"

            i=1
            for f in $(ls .github/workflows/*.yaml | sort); do
              base=$(basename "$f")
              pkg=$(basename "$f" .yaml)
              if [ "$base" = "README.yaml" ]; then
                continue
              fi
              if [ "$base" = "deploy-page.yaml" ]; then
                continue
              fi
              link="$REPO_URL/blob/main/.github/workflows/$base"
              echo "| $i | $pkg | [${base}](${link}) |"
              i=$((i+1))
            done

            echo ""
            echo "（本表格由 GitHub Actions 自动生成）"
            echo ""
            echo "---"
            echo ""
            echo "## ⚙️ 自动化说明"
            echo ""
            echo "- 每个包的构建规则定义在 \`.github/workflows/\` 目录下；"
            echo "- 本工作流每天自动运行一次；"
            echo "- 若检测到新增或删除的 YAML 文件，将自动更新 README；"
            echo "- 当前的 \`README.yaml\` 文件不会被计入列表。"
            echo ""
            echo "---"
            echo ""
            echo "## 🕒 更新时间"
            echo ""
            echo "- 世界标准时间 (UTC)：\`$(date -u '+%Y-%m-%d %H:%M:%S')\`"
            echo "- 北京时间 (Asia/Shanghai)：\`$(date '+%Y-%m-%d %H:%M:%S')\`"
          } > tmp/README_zh.md

          mv tmp/README.md README.md
          mv tmp/README_zh.md README_zh.md
          rm -rf tmp

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet README.md README_zh.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md README_zh.md
          git commit -m "auto: update bilingual README files with current workflows"
          git push

