name: 🧾 Update README & Docs (Bilingual + Package List)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*.yaml"

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repository info
        id: repo
        run: |
          REPO_URL=$(git config --get remote.origin.url | sed 's/.git$//')
          echo "repo_url=${REPO_URL}" >> $GITHUB_OUTPUT

      - name: Generate bilingual README and docs
        run: |
          REPO_URL="${{ steps.repo.outputs.repo_url }}"
          mkdir -p tmp docs

          # --- README English ---
          {
            echo "# 🏗️ LoongArch Python Package Build CI"
            echo ""
            echo "[简体中文](./README_zh.md)"
            echo ""
            echo "This repository automatically builds and maintains **Python (pip) packages** for the **LoongArch (loongarch64)** architecture."
            echo ""
            echo "---"
            echo ""
            echo "## 📦 Supported Build Workflows"
            echo ""
            echo "| No. | Package | Workflow |"
            echo "|-----|----------|-----------|"

            i=1
            for f in $(ls .github/workflows/*.yaml | sort); do
              base=$(basename "$f")
              pkg=$(basename "$f" .yaml)
              if [[ "$base" == "readme-sync.yaml" || "$base" == "deploy-page.yaml" ]]; then
                continue
              fi
              link="$REPO_URL/blob/main/.github/workflows/$base"
              echo "| $i | $pkg | [${base}](${link}) |"
              i=$((i+1))
            done

            echo ""
            echo "_This table is automatically generated by GitHub Actions._"
            echo ""
            echo "---"
            echo ""
            echo "## ⚙️ Automation Details"
            echo ""
            echo "- Each package has a dedicated workflow under \`.github/workflows/\`."
            echo "- This workflow runs **daily** and regenerates README when workflow files change."
            echo ""
            echo "---"
            echo ""
            echo "## 🕒 Last Updated"
            echo ""
            echo "- UTC Time: \`$(date -u '+%Y-%m-%d %H:%M:%S')\`"
            echo "- Local Time (Asia/Shanghai): \`$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')\`"
          } > tmp/README.md

          # --- README 中文 ---
          {
            echo "# 🏗️ LoongArch Python 包构建自动化仓库"
            echo ""
            echo "[English](./README.md)"
            echo ""
            echo "本仓库用于自动构建和维护 **LoongArch（loongarch64）** 架构下的 **Python 第三方库（pip 包）**。"
            echo ""
            echo "---"
            echo ""
            echo "## 📦 当前支持的构建任务"
            echo ""
            echo "| 序号 | 包名称 | Workflow 文件 |"
            echo "|------|----------|----------------|"

            i=1
            for f in $(ls .github/workflows/*.yaml | sort); do
              base=$(basename "$f")
              pkg=$(basename "$f" .yaml)
              if [[ "$base" == "readme-sync.yaml" || "$base" == "deploy-page.yaml" ]]; then
                continue
              fi
              link="$REPO_URL/blob/main/.github/workflows/$base"
              echo "| $i | $pkg | [${base}](${link}) |"
              i=$((i+1))
            done

            echo ""
            echo "（本表格由 GitHub Actions 自动生成）"
            echo ""
            echo "---"
            echo ""
            echo "## ⚙️ 自动化说明"
            echo ""
            echo "- 每个包的构建规则定义在 \`.github/workflows/\` 目录下；"
            echo "- 工作流每天自动运行一次；"
            echo "- 若检测到新增或删除的 YAML 文件，将自动更新 README；"
          } > tmp/README_zh.md

          # --- 自动生成 MkDocs docs/package-list.md ---
          {
            echo "# 📚 LoongArch Python Packages List"
            echo ""
            echo "| No. | Package | Workflow |"
            echo "|-----|---------|---------|"

            i=1
            for f in $(ls .github/workflows/*.yaml | sort); do
              base=$(basename "$f")
              pkg=$(basename "$f" .yaml)
              if [[ "$base" == "readme-sync.yaml" || "$base" == "deploy-page.yaml" ]]; then
                continue
              fi
              link="$REPO_URL/blob/main/.github/workflows/$base"
              echo "| $i | $pkg | [${base}](${link}) |"
              i=$((i+1))
            done

            echo ""
            echo "_This table is automatically generated by GitHub Actions._"
          } > docs/package-list.md

          mv tmp/README.md README.md
          mv tmp/README_zh.md README_zh.md
          rm -rf tmp

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet README.md README_zh.md docs/package-list.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md README_zh.md docs/package-list.md
          git commit -m "auto: update bilingual README and package list docs"
          git push

