name: 🧾 Update README with Workflow List

on:
  schedule:
    - cron: "0 3 * * *" 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/*.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate bilingual README.md
        run: |
          echo "# 🏗️ LoongArch Python Package Build CI" > README.md
          echo "" >> README.md
          echo "This repository automatically builds and maintains **Python packages (pip)** for the **LoongArch (loongarch64)** architecture." >> README.md
          echo "" >> README.md
          echo "本仓库用于自动构建和维护 **LoongArch 平台（loongarch64）** 下的 Python 第三方库（pip 包）。" >> README.md
          echo "" >> README.md

          echo "---" >> README.md
          echo "" >> README.md
          echo "## 📦 Supported Build Workflows" >> README.md
          echo "" >> README.md
          echo "以下为自动生成的构建工作流列表：" >> README.md
          echo "" >> README.md

          echo "| No. | Package Name | Workflow File | 包名称 |" >> README.md
          echo "|-----|---------------|----------------|--------|" >> README.md

          i=1
          for f in $(ls .github/workflows/*.yaml | sort); do
            pkg=$(basename "$f" .yaml)
            echo "| $i | $pkg | \`$(basename $f)\` | $pkg |" >> README.md
            i=$((i+1))
          done

          echo "" >> README.md
          echo "（This table is automatically generated by GitHub Actions）" >> README.md
          echo "" >> README.md
          echo "（本表格由 GitHub Actions 自动生成）" >> README.md
          echo "" >> README.md

          echo "---" >> README.md
          echo "" >> README.md
          echo "## ⚙️ Automation Details" >> README.md
          echo "" >> README.md
          echo "- Each package build is defined in a YAML file under \`.github/workflows/\`." >> README.md
          echo "- The workflow **runs daily** and checks for new or removed YAML files." >> README.md
          echo "- When a new file is detected, this README is automatically updated and committed." >> README.md
          echo "" >> README.md
          echo "- 每个包的构建规则定义在 \`.github/workflows/\` 目录下的 YAML 文件中；" >> README.md
          echo "- CI **每天自动运行一次**，检测新增或删除的构建文件；" >> README.md
          echo "- 若检测到变动，自动更新并提交 README。" >> README.md
          echo "" >> README.md

          echo "---" >> README.md
          echo "" >> README.md
          echo "## 🕒 Last Updated" >> README.md
          echo "" >> README.md
          echo "- UTC Time: \`$(date -u '+%Y-%m-%d %H:%M:%S')\`" >> README.md
          echo "- Local Time (Asia/Shanghai): \`$(date '+%Y-%m-%d %H:%M:%S')\`" >> README.md

      - name: Check if README changed
        id: git-check
        run: |
          if git diff --quiet README.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "auto: update bilingual README with current workflows"
          git push

